// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/devhg/es/internal/biz"
	"github.com/devhg/es/internal/conf"
	"github.com/devhg/es/internal/data"
	"github.com/devhg/es/internal/server"
	"github.com/devhg/es/internal/service"
	"net/http"
)

// Injectors from wire.go:

// initApp init application.
func initApp(config *conf.Config) (*http.Server, func()) {
	client := data.NewEsClient(config)
	userEsProvider := biz.NewUserEsProvider(client)
	userService := service.NewUserService(userEsProvider)
	httpServer, cleanup := server.NewHTTPServer(config, userService)
	return httpServer, func() {
		cleanup()
	}
}
